### ISSUE TITLE
When will baseline results be updated？

### ISSUE THREAD

**Issue by rookie0607** [microsoft/NOTSOFAR1-Challenge#28]

**Comment by nidleo** [comment]
Hi, 
It will be up early next week. We'll have it ready before the leaderboard goes live.

**Comment by rookie0607** [comment]
> Hi, It will be up early next week. We'll have it ready before the leaderboard goes live.

Thank you for your reply, I have another question for you, I am using azcopy to download the simulation data used for css training keeps interrupting, ERROR LOG:.
2024-02-22 14:21:28,912 [INFO] [azure_storage] Downloading to temp dir first: /tmp/tmp9mivr0cw
INFO: scanning...
INFO: will not process any empty folders, as the source and/or target does not support full folders

Task 4d0542a2-a3a6-e844-6c3e-d8367fb18524 started
Log file located at /root/.azcopy/4d0542a2-a3a6-e844-6c3e-d8367fb18524.log

19.6 %, 1963 Done, 0 Failed, 8037 Pending, 0 Skipped, 10000 Total (scanning...) , 2-sec Throughput (Mb/s): 81.9549
Failed to execute replication command due to error: unable to start job due to error: unable to list file due to reason Read tcp x.x.x.x:x->20.157.50.176:443: Read: Connection was reset by peer.


Translated with DeepL.com (free version)
