### ISSUE TITLE
Second batch of 30 hours of meeting recordings train-set release

### ISSUE THREAD

**Issue by EyalCohenResearch** [microsoft/NOTSOFAR1-Challenge#32]
Hi,

In the MS challenge's important dates, you mentioned that the second batch of 30 hours should be published on March 1st, 2024. However, the version in
`download_meeting_subset(subset_name='train_set', version='240208.2_train', destination_dir=...)` has not been updated since [Feb 13](https://github.com/microsoft/NOTSOFAR1-Challenge/pull/25).
Does `'240208.2_train'` version include the new 30-hour subset? If not, when do you plan to upload it?

Thanks!

**Comment by nidleo** [comment]
Thanks for reaching out!
We're working on a package of upgrades, including the second batch train-set, latest baseline results, and a live leaderboard.
The github and [CHiME ](https://www.chimechallenge.org/current/task2/index)websites will reflect these changes in 1-2 days.

Meanwhile, you can already access the latest training set with:
`download_meeting_subset(subset_name='train_set', version='240229.1_train', destination_dir=...)`

`240229.1_train` includes the first and second batches of training.

**Comment by nidleo** [comment]
The site has been [updated](https://www.chimechallenge.org/current/task2/index#dates). Closing.
