### ISSUE TITLE
CUFFT_INTERNAL_ERROR for certain hardware

### ISSUE THREAD

**Issue by SamuelBroughton** [microsoft/NOTSOFAR1-Challenge#40]
Installing the repo as described will install torch with cuda 11.7

If you are using a device such as RTX 4090, you will get an error when trying to do diarization with nemo.

For example, if you just run `python run_inference.py` you will get an error similar to this when torch.stft is called:

```
NOTSOFAR1-Challenge/diarization/word_based_diarization.py", line 105, in extract_speaker_embedding_for_words
    _, tmp_embedding = spk_model.forward(input_signal=word_wavs, input_signal_length=word_lens)

...

RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR
```

As https://github.com/pytorch/pytorch/issues/88038 suggests, cuda 11.8 fixes the issue.

Ugrading pytorch to the latest stable version with cuda 11.8 fixes the issue, `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`

**Comment by nidleo** [comment]
Thank you @SamuelBroughton for reporting this issue and providing a fix. 
We will consider updating the environment to use cu118. However, since this requires some testing for both training and inference, it may take some time before we can implement the change.
