### ISSUE TITLE
Pretrained CSS model

### ISSUE THREAD

**Issue by kfmn** [microsoft/NOTSOFAR1-Challenge#53]
Hi,

Is any CSS model trained with the provided baseline and NOTSOFAR-1 data available? Where it can be downloaded if any?

Thanks.

**Comment by nidleo** [comment]
Hi,
Running the inference pipeline will download the model checkpoint automatically. 
See here:
https://github.com/microsoft/NOTSOFAR1-Challenge?tab=readme-ov-file#running-evaluation---the-inference-pipeline

Note there are two models, mc and sc, each downloaded according to the config.

Alternatively, you can call 'download_models' from this module:
https://github.com/microsoft/NOTSOFAR1-Challenge/blob/main/utils/azure_storage.py

**Comment by kfmn** [comment]
Thank you very much
